- name: Set Prompt
  ansible.builtin.shell: set-prompt {{ tool_name }}

- name: LVM Layout
  ansible.builtin.include_role:
      name: common
      tasks_from: lvm

- name: Copy Elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install ELK
  ansible.builtin.dnf:
    name:
      - elasticsearch
      - kibana
      - logstash
      - nginx
    state: installed

- name: Copy nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start ELK
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - elasticsearch
    - kibana
    - logstash
    - nginx

- name: Copy Logstash configuration
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
  notify: Restart Logstash